"""add printer_state table

Revision ID: 4babfb84a9a0
Revises: e0d573b37f5b
Create Date: 2026-05-16 12:47:04.479814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4babfb84a9a0'
down_revision: Union[str, Sequence[str], None] = 'e0d573b37f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printer_state',
    sa.Column('printer_id', sa.Uuid(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.PrimaryKeyConstraint('printer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('printer_state')
    # ### end Alembic commands ###
