"""add templates table

Revision ID: 54f963fdb994
Revises: b1a0b028aabb
Create Date: 2026-05-16 12:38:43.786887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54f963fdb994'
down_revision: Union[str, Sequence[str], None] = 'b1a0b028aabb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('app', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('printer_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tape_width_mm', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source IN ('seed', 'user')", name='ck_templates_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_key'), 'templates', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_key'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
