"""add print_batches table

Revision ID: a0516c04278c
Revises: da865401716d
Create Date: 2026-05-30 15:18:58.348408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0516c04278c'
down_revision: Union[str, Sequence[str], None] = 'da865401716d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('print_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('printer_id', sa.Uuid(), nullable=False),
    sa.Column('job_ids', sa.JSON(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_batches_created_at'), 'print_batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_print_batches_created_by'), 'print_batches', ['created_by'], unique=False)
    op.create_index(op.f('ix_print_batches_printer_id'), 'print_batches', ['printer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_print_batches_printer_id'), table_name='print_batches')
    op.drop_index(op.f('ix_print_batches_created_by'), table_name='print_batches')
    op.drop_index(op.f('ix_print_batches_created_at'), table_name='print_batches')
    op.drop_table('print_batches')
    # ### end Alembic commands ###
