"""add printer_status_cache table

Revision ID: b2668b6e8845
Revises: 4babfb84a9a0
Create Date: 2026-05-16 12:48:06.110089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2668b6e8845'
down_revision: Union[str, Sequence[str], None] = '4babfb84a9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printer_status_cache',
    sa.Column('printer_id', sa.Uuid(), nullable=False),
    sa.Column('raw_block', sa.LargeBinary(), nullable=True),
    sa.Column('parsed', sa.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.PrimaryKeyConstraint('printer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('printer_status_cache')
    # ### end Alembic commands ###
