// Package api provides a typed HTTP client for the label-printer-hub backend API.
//
// The generated client (client.gen.go) is produced by oapi-codegen from the
// backend's OpenAPI spec (openapi.snapshot.json). This file adds:
//   - NewClientMust: panic-on-error wrapper around the generated NewClient
//   - Typed convenience methods on *ClientWithResponses
//   - Sentinel errors ErrNotFound and ErrUnsupportedApp
//
// Regenerate with: make gen-client (requires oapi-codegen in PATH).
// The generated file is committed so go build works without a live backend.
//
// Type aliases
// ------------
// PrinterRead is an alias for AppSchemasPrinterPrinterRead — the oapi-codegen
// name changed when the admin-printers schema was added (two schemas named
// "PrinterRead" require namespace-qualified names). Callers continue to use
// PrinterRead unchanged.
//
// TemplateRead is kept as a local struct (GET /api/templates was removed from
// the backend in Phase 1k.1a, Issue #103). The handler code that still calls
// ListTemplates will receive a "not implemented" error until the routes are
// cleaned up in a follow-up task.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// PrinterRead is a backward-compat alias for the oapi-codegen generated type.
// When the admin-printers schema was added (Issue #124 Task 7.2), oapi-codegen
// disambiguated the two "PrinterRead" schemas from different route modules by
// prefixing them with their package path. All frontend code continues to use
// PrinterRead via this alias.
type PrinterRead = AppSchemasPrinterPrinterRead

// TemplateRead is kept locally because GET /api/templates was removed from the
// backend in Phase 1k.1a (Issue #103). The handlers that render the templates
// pages still reference this type; they will receive ErrNotImplemented from
// ListTemplates until a follow-up task removes the template routes.
//
// TODO(#103): Remove TemplateRead and all template handler code once the routes
// are cleaned up.
type TemplateRead struct {
	App          string                 `json:"app"`
	CreatedAt    string                 `json:"created_at"`
	Definition   map[string]interface{} `json:"definition"`
	Id           string                 `json:"id"`
	Key          string                 `json:"key"`
	Name         string                 `json:"name"`
	PrinterModel string                 `json:"printer_model"`
	SchemaVersion int                   `json:"schema_version"`
	Source       string                 `json:"source"`
	TapeWidthMm  int                    `json:"tape_width_mm"`
	UpdatedAt    string                 `json:"updated_at"`
}

// ErrNotImplemented is returned by client methods whose backend endpoint has
// been removed. Callers should treat this as "feature not available".
var ErrNotImplemented = fmt.Errorf("not implemented")

// HubClient is the typed HTTP client used by frontend handlers.
// It wraps ClientWithResponses (generated by oapi-codegen) with convenience
// methods, structured logging, and sentinel errors.
//
// Use NewHubClient to construct.
// Use WithAuthFrom to create a scoped copy that forwards auth headers from an
// incoming browser request to all outgoing backend calls.
type HubClient struct {
	gen         *ClientWithResponses
	hc          *http.Client // shared client used for raw requests (RenderPreview, CheckHealth)
	baseURL     string
	authHeaders map[string]string // auth headers injected into every backend call
}

var (
	// ErrNotFound is returned by client methods when the backend responds with 404.
	ErrNotFound = fmt.Errorf("not found")

	// ErrUnsupportedApp is returned when the backend responds with 422 (unknown app).
	ErrUnsupportedApp = fmt.Errorf("unsupported app")
)

// NewHubClient constructs a HubClient that targets the given backend base URL.
// backendURL must not have a trailing slash (e.g. "http://backend:8000").
// Panics if the URL is invalid.
//
// This is distinct from the oapi-codegen-generated NewClient() which returns
// the low-level (*Client, error) — NewHubClient is the constructor for
// handler code and tests.
func NewHubClient(backendURL string) *HubClient {
	hc := &http.Client{Timeout: 10 * time.Second}
	gen, err := NewClientWithResponses(backendURL, WithHTTPClient(hc))
	if err != nil {
		panic("api.NewClient: " + err.Error())
	}
	return &HubClient{gen: gen, hc: hc, baseURL: backendURL}
}

// BaseURL returns the backend base URL this client targets.
func (c *HubClient) BaseURL() string {
	return c.baseURL
}

// WithAuthFrom returns a new HubClient that copies auth-related headers from
// the incoming browser request into every outgoing backend call.
//
// The headers forwarded are:
//   - X-Label-Hub-Key   — API-key auth (Phase 7c)
//   - X-Pangolin-User   — Pangolin SSO session header (Legacy / Standard SSO)
//   - X-Pangolin-Token  — Pangolin Resource custom upstream header (Trust-Token)
//   - Authorization     — Pangolin Basic-Auth bypass (claude-automation)
//
// This is required because the frontend-to-backend calls are internal
// (Docker-network, no Pangolin in between) and the backend's Phase 7c auth
// middleware rejects requests that carry none of these headers with 401.
//
// X-Pangolin-Token is the static trust-token that a Pangolin Resource can
// inject into every upstream request via its Header-Auth configuration. The
// backend's sso_trust_header mechanism accepts it as a SSO-equivalent signal,
// which is what allows browser users without an active SSO session to still
// reach the UI.
//
// The original HubClient is not mutated; the returned copy shares the same
// underlying http.Client and gen client but adds a RequestEditorFn that
// injects the auth headers.
func (c *HubClient) WithAuthFrom(r *http.Request) *HubClient {
	headers := make(map[string]string, 4)
	for _, h := range []string{"X-Label-Hub-Key", "X-Pangolin-User", "X-Pangolin-Token", "Authorization"} {
		if v := r.Header.Get(h); v != "" {
			headers[h] = v
		}
	}
	return &HubClient{
		gen:         c.gen,
		hc:          c.hc,
		baseURL:     c.baseURL,
		authHeaders: headers,
	}
}

// authEditor returns a RequestEditorFn that injects the stored auth headers
// into every outgoing request. Returns nil when no auth headers are configured
// (no-auth path — tests, health-checks).
func (c *HubClient) authEditor() RequestEditorFn {
	if len(c.authHeaders) == 0 {
		return nil
	}
	headers := c.authHeaders // capture for closure
	return func(_ context.Context, req *http.Request) error {
		for k, v := range headers {
			req.Header.Set(k, v)
		}
		return nil
	}
}

// editors returns the RequestEditorFn slice to pass to generated client methods.
// Empty when no auth headers are configured.
func (c *HubClient) editors() []RequestEditorFn {
	if ed := c.authEditor(); ed != nil {
		return []RequestEditorFn{ed}
	}
	return nil
}

func logCall(op string, start time.Time, err error) {
	slog.Debug("backend call", "op", op, "ms", time.Since(start).Milliseconds(), "err", err)
}

// ListPrinters returns all printers from GET /api/printers.
func (c *HubClient) ListPrinters(ctx context.Context) ([]PrinterRead, error) {
	start := time.Now()
	resp, err := c.gen.ListPrintersApiPrintersGetWithResponse(ctx, nil, c.editors()...)
	logCall("ListPrinters", start, err)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, fmt.Errorf("ListPrinters: status %d", resp.StatusCode())
	}
	return *resp.JSON200, nil
}

// GetPrinterDetail returns full printer metadata from GET /api/printers/{id}.
func (c *HubClient) GetPrinterDetail(ctx context.Context, id string) (*PrinterRead, error) {
	start := time.Now()
	uid, err := parseUUID(id)
	if err != nil {
		return nil, ErrNotFound
	}
	resp, err := c.gen.GetPrinterApiPrintersPrinterIdGetWithResponse(ctx, uid, c.editors()...)
	logCall("GetPrinterDetail", start, err)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode() == http.StatusNotFound {
		return nil, ErrNotFound
	}
	if resp.JSON200 == nil {
		return nil, fmt.Errorf("GetPrinterDetail: status %d", resp.StatusCode())
	}
	return resp.JSON200, nil
}

// GetPrinterStatus returns a fresh printer status probe from GET /api/printers/{id}/status.
func (c *HubClient) GetPrinterStatus(ctx context.Context, id string) (*PrinterStatus, error) {
	start := time.Now()
	uid, err := parseUUID(id)
	if err != nil {
		return nil, ErrNotFound
	}
	resp, err := c.gen.GetPrinterStatusApiPrintersPrinterIdStatusGetWithResponse(ctx, uid, c.editors()...)
	logCall("GetPrinterStatus", start, err)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode() == http.StatusNotFound {
		return nil, ErrNotFound
	}
	if resp.JSON200 == nil {
		return nil, fmt.Errorf("GetPrinterStatus: status %d", resp.StatusCode())
	}
	return resp.JSON200, nil
}

// GetPrinterTape returns the tape spec from GET /api/printers/{id}/tape.
func (c *HubClient) GetPrinterTape(ctx context.Context, id string) (map[string]any, error) {
	start := time.Now()
	uid, err := parseUUID(id)
	if err != nil {
		return nil, ErrNotFound
	}
	resp, err := c.gen.GetPrinterTapeApiPrintersPrinterIdTapeGetWithResponse(ctx, uid, c.editors()...)
	logCall("GetPrinterTape", start, err)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode() == http.StatusNotFound {
		return nil, ErrNotFound
	}
	if resp.JSON200 == nil {
		return nil, fmt.Errorf("GetPrinterTape: status %d", resp.StatusCode())
	}
	return *resp.JSON200, nil
}

// GetPrinterQueue returns active jobs from GET /api/printers/{id}/queue.
func (c *HubClient) GetPrinterQueue(ctx context.Context, id string) ([]map[string]any, error) {
	start := time.Now()
	uid, err := parseUUID(id)
	if err != nil {
		return nil, ErrNotFound
	}
	resp, err := c.gen.GetPrinterQueueApiPrintersPrinterIdQueueGetWithResponse(ctx, uid, c.editors()...)
	logCall("GetPrinterQueue", start, err)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, fmt.Errorf("GetPrinterQueue: status %d", resp.StatusCode())
	}
	return *resp.JSON200, nil
}

// ListJobs returns jobs matching the given filters from GET /api/jobs.
func (c *HubClient) ListJobs(ctx context.Context, params *ListJobsApiJobsGetParams) ([]JobRead, error) {
	start := time.Now()
	resp, err := c.gen.ListJobsApiJobsGetWithResponse(ctx, params, c.editors()...)
	logCall("ListJobs", start, err)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, fmt.Errorf("ListJobs: status %d", resp.StatusCode())
	}
	return *resp.JSON200, nil
}

// GetJob returns a single job by ID from GET /api/jobs/{id}.
func (c *HubClient) GetJob(ctx context.Context, id string) (*JobRead, error) {
	start := time.Now()
	uid, err := parseUUID(id)
	if err != nil {
		return nil, ErrNotFound
	}
	resp, err := c.gen.GetJobApiJobsJobIdGetWithResponse(ctx, uid, c.editors()...)
	logCall("GetJob", start, err)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode() == http.StatusNotFound {
		return nil, ErrNotFound
	}
	if resp.JSON200 == nil {
		return nil, fmt.Errorf("GetJob: status %d", resp.StatusCode())
	}
	return resp.JSON200, nil
}

// RetryJob clones a failed job via POST /api/jobs/{id}/retry and returns the new job ID.
func (c *HubClient) RetryJob(ctx context.Context, id string) (string, error) {
	start := time.Now()
	uid, err := parseUUID(id)
	if err != nil {
		return "", ErrNotFound
	}
	resp, err := c.gen.RetryJobApiJobsJobIdRetryPostWithResponse(ctx, uid, c.editors()...)
	logCall("RetryJob", start, err)
	if err != nil {
		return "", err
	}
	if resp.StatusCode() == http.StatusNotFound {
		return "", ErrNotFound
	}
	if resp.JSON201 == nil {
		return "", fmt.Errorf("RetryJob: status %d", resp.StatusCode())
	}
	return resp.JSON201.Id.String(), nil
}

// ListTemplates is a stub that returns ErrNotImplemented.
//
// GET /api/templates was removed from the backend in Phase 1k.1a (Issue #103)
// when the semantic LayoutEngine replaced the static template system.
// The method signature is kept so existing handler code compiles; a follow-up
// task (#103) will remove the template routes and handlers entirely.
func (c *HubClient) ListTemplates(_ context.Context, _ string) ([]TemplateRead, error) {
	return nil, ErrNotImplemented
}

// LookupEntity resolves an integration entity via GET /api/lookup/{app}/{id}.
//
// Uses the raw (non-WithResponse) generated client to avoid a JSON parse
// error on 422 responses. The backend may return a non-standard 422 body
// ({"detail": "unknown app"} with detail as a string), which would fail
// parsing into HTTPValidationError.Detail (*[]ValidationError). By using
// the raw client we read the status code directly and return sentinel errors.
func (c *HubClient) LookupEntity(ctx context.Context, app, id string) (*LookupResult, error) {
	start := time.Now()
	appParam := LookupApiLookupAppEntityIdGetParamsApp(app)
	rawResp, err := c.gen.LookupApiLookupAppEntityIdGet(ctx, appParam, id, c.editors()...)
	logCall("LookupEntity", start, err)
	if err != nil {
		return nil, err
	}
	defer rawResp.Body.Close()
	switch rawResp.StatusCode {
	case http.StatusNotFound:
		return nil, ErrNotFound
	case http.StatusUnprocessableEntity:
		return nil, ErrUnsupportedApp
	case http.StatusOK:
		// fall through to parse the body
	default:
		return nil, fmt.Errorf("LookupEntity: status %d", rawResp.StatusCode)
	}
	var result LookupResult
	if err := json.NewDecoder(rawResp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("LookupEntity: decode: %w", err)
	}
	return &result, nil
}

// RenderPreview requests a PNG preview for a template from POST /api/render/preview.
// Returns the raw PNG bytes on success, or an error when the endpoint is unavailable
// or the render fails. Callers should treat any error as "show placeholder" — the
// endpoint is optional and may not yet be implemented by all backend versions.
func (c *HubClient) RenderPreview(ctx context.Context, templateKey string) ([]byte, error) {
	start := time.Now()
	previewURL := c.baseURL + "/api/render/preview?key=" + url.QueryEscape(templateKey)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, previewURL, nil)
	if err != nil {
		return nil, err
	}
	resp, err := c.hc.Do(req)
	logCall("RenderPreview", start, err)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("RenderPreview: status %d", resp.StatusCode)
	}
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

// CheckHealth performs a GET /healthz against the backend and returns an error if unavailable.
func (c *HubClient) CheckHealth(ctx context.Context) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, c.baseURL+"/healthz", nil)
	if err != nil {
		return err
	}
	resp, err := c.hc.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("backend healthz: %d", resp.StatusCode)
	}
	return nil
}

// parseUUID parses a string into an openapi_types.UUID.
func parseUUID(s string) (openapi_types.UUID, error) {
	var u openapi_types.UUID
	err := u.UnmarshalText([]byte(s))
	return u, err
}
