// Package api provides a typed HTTP client for the label-printer-hub backend API.
//
// The generated client (client.gen.go) is produced by oapi-codegen from the
// backend's OpenAPI spec (openapi.snapshot.json). This file adds:
//   - NewClientMust: panic-on-error wrapper around the generated NewClient
//   - Typed convenience methods on *ClientWithResponses
//   - Sentinel errors ErrNotFound and ErrUnsupportedApp
//
// Regenerate with: make gen-client (requires oapi-codegen in PATH).
// The generated file is committed so go build works without a live backend.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// HubClient is the typed HTTP client used by frontend handlers.
// It wraps ClientWithResponses (generated by oapi-codegen) with convenience
// methods, structured logging, and sentinel errors.
//
// Use NewHubClient to construct.
type HubClient struct {
	gen     *ClientWithResponses
	hc      *http.Client // shared client used for raw requests (RenderPreview, CheckHealth)
	baseURL string
}

var (
	// ErrNotFound is returned by client methods when the backend responds with 404.
	ErrNotFound = fmt.Errorf("not found")

	// ErrUnsupportedApp is returned when the backend responds with 422 (unknown app).
	ErrUnsupportedApp = fmt.Errorf("unsupported app")
)

// NewHubClient constructs a HubClient that targets the given backend base URL.
// backendURL must not have a trailing slash (e.g. "http://backend:8000").
// Panics if the URL is invalid.
//
// This is distinct from the oapi-codegen-generated NewClient() which returns
// the low-level (*Client, error) — NewHubClient is the constructor for
// handler code and tests.
func NewHubClient(backendURL string) *HubClient {
	hc := &http.Client{Timeout: 10 * time.Second}
	gen, err := NewClientWithResponses(backendURL, WithHTTPClient(hc))
	if err != nil {
		panic("api.NewClient: " + err.Error())
	}
	return &HubClient{gen: gen, hc: hc, baseURL: backendURL}
}

func logCall(op string, start time.Time, err error) {
	slog.Debug("backend call", "op", op, "ms", time.Since(start).Milliseconds(), "err", err)
}

// ListPrinters returns all printers from GET /api/printers.
func (c *HubClient) ListPrinters(ctx context.Context) ([]PrinterRead, error) {
	start := time.Now()
	resp, err := c.gen.ListPrintersApiPrintersGetWithResponse(ctx)
	logCall("ListPrinters", start, err)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, fmt.Errorf("ListPrinters: status %d", resp.StatusCode())
	}
	return *resp.JSON200, nil
}

// GetPrinterDetail returns full printer metadata from GET /api/printers/{id}.
func (c *HubClient) GetPrinterDetail(ctx context.Context, id string) (*PrinterRead, error) {
	start := time.Now()
	uid, err := parseUUID(id)
	if err != nil {
		return nil, ErrNotFound
	}
	resp, err := c.gen.GetPrinterApiPrintersPrinterIdGetWithResponse(ctx, uid)
	logCall("GetPrinterDetail", start, err)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode() == http.StatusNotFound {
		return nil, ErrNotFound
	}
	if resp.JSON200 == nil {
		return nil, fmt.Errorf("GetPrinterDetail: status %d", resp.StatusCode())
	}
	return resp.JSON200, nil
}

// GetPrinterStatus returns a fresh printer status probe from GET /api/printers/{id}/status.
func (c *HubClient) GetPrinterStatus(ctx context.Context, id string) (*PrinterStatus, error) {
	start := time.Now()
	uid, err := parseUUID(id)
	if err != nil {
		return nil, ErrNotFound
	}
	resp, err := c.gen.GetPrinterStatusApiPrintersPrinterIdStatusGetWithResponse(ctx, uid)
	logCall("GetPrinterStatus", start, err)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode() == http.StatusNotFound {
		return nil, ErrNotFound
	}
	if resp.JSON200 == nil {
		return nil, fmt.Errorf("GetPrinterStatus: status %d", resp.StatusCode())
	}
	return resp.JSON200, nil
}

// GetPrinterTape returns the tape spec from GET /api/printers/{id}/tape.
func (c *HubClient) GetPrinterTape(ctx context.Context, id string) (map[string]any, error) {
	start := time.Now()
	uid, err := parseUUID(id)
	if err != nil {
		return nil, ErrNotFound
	}
	resp, err := c.gen.GetPrinterTapeApiPrintersPrinterIdTapeGetWithResponse(ctx, uid)
	logCall("GetPrinterTape", start, err)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode() == http.StatusNotFound {
		return nil, ErrNotFound
	}
	if resp.JSON200 == nil {
		return nil, fmt.Errorf("GetPrinterTape: status %d", resp.StatusCode())
	}
	return *resp.JSON200, nil
}

// GetPrinterQueue returns active jobs from GET /api/printers/{id}/queue.
func (c *HubClient) GetPrinterQueue(ctx context.Context, id string) ([]map[string]any, error) {
	start := time.Now()
	uid, err := parseUUID(id)
	if err != nil {
		return nil, ErrNotFound
	}
	resp, err := c.gen.GetPrinterQueueApiPrintersPrinterIdQueueGetWithResponse(ctx, uid)
	logCall("GetPrinterQueue", start, err)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, fmt.Errorf("GetPrinterQueue: status %d", resp.StatusCode())
	}
	return *resp.JSON200, nil
}

// ListJobs returns jobs matching the given filters from GET /api/jobs.
func (c *HubClient) ListJobs(ctx context.Context, params *ListJobsApiJobsGetParams) ([]JobRead, error) {
	start := time.Now()
	resp, err := c.gen.ListJobsApiJobsGetWithResponse(ctx, params)
	logCall("ListJobs", start, err)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, fmt.Errorf("ListJobs: status %d", resp.StatusCode())
	}
	return *resp.JSON200, nil
}

// GetJob returns a single job by ID from GET /api/jobs/{id}.
func (c *HubClient) GetJob(ctx context.Context, id string) (*JobRead, error) {
	start := time.Now()
	uid, err := parseUUID(id)
	if err != nil {
		return nil, ErrNotFound
	}
	resp, err := c.gen.GetJobApiJobsJobIdGetWithResponse(ctx, uid)
	logCall("GetJob", start, err)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode() == http.StatusNotFound {
		return nil, ErrNotFound
	}
	if resp.JSON200 == nil {
		return nil, fmt.Errorf("GetJob: status %d", resp.StatusCode())
	}
	return resp.JSON200, nil
}

// RetryJob clones a failed job via POST /api/jobs/{id}/retry and returns the new job ID.
func (c *HubClient) RetryJob(ctx context.Context, id string) (string, error) {
	start := time.Now()
	uid, err := parseUUID(id)
	if err != nil {
		return "", ErrNotFound
	}
	resp, err := c.gen.RetryJobApiJobsJobIdRetryPostWithResponse(ctx, uid)
	logCall("RetryJob", start, err)
	if err != nil {
		return "", err
	}
	if resp.StatusCode() == http.StatusNotFound {
		return "", ErrNotFound
	}
	if resp.JSON201 == nil {
		return "", fmt.Errorf("RetryJob: status %d", resp.StatusCode())
	}
	return resp.JSON201.Id.String(), nil
}

// ListTemplates returns all templates, optionally filtered by app, from GET /api/templates.
func (c *HubClient) ListTemplates(ctx context.Context, app string) ([]TemplateRead, error) {
	start := time.Now()
	var params *ListTemplatesApiTemplatesGetParams
	if app != "" {
		params = &ListTemplatesApiTemplatesGetParams{App: &app}
	}
	resp, err := c.gen.ListTemplatesApiTemplatesGetWithResponse(ctx, params)
	logCall("ListTemplates", start, err)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, fmt.Errorf("ListTemplates: status %d", resp.StatusCode())
	}
	return *resp.JSON200, nil
}

// LookupEntity resolves an integration entity via GET /api/lookup/{app}/{id}.
//
// Uses the raw (non-WithResponse) generated client to avoid a JSON parse
// error on 422 responses. The backend may return a non-standard 422 body
// ({"detail": "unknown app"} with detail as a string), which would fail
// parsing into HTTPValidationError.Detail (*[]ValidationError). By using
// the raw client we read the status code directly and return sentinel errors.
func (c *HubClient) LookupEntity(ctx context.Context, app, id string) (*LookupResult, error) {
	start := time.Now()
	appParam := LookupApiLookupAppEntityIdGetParamsApp(app)
	rawResp, err := c.gen.LookupApiLookupAppEntityIdGet(ctx, appParam, id)
	logCall("LookupEntity", start, err)
	if err != nil {
		return nil, err
	}
	defer rawResp.Body.Close()
	switch rawResp.StatusCode {
	case http.StatusNotFound:
		return nil, ErrNotFound
	case http.StatusUnprocessableEntity:
		return nil, ErrUnsupportedApp
	case http.StatusOK:
		// fall through to parse the body
	default:
		return nil, fmt.Errorf("LookupEntity: status %d", rawResp.StatusCode)
	}
	var result LookupResult
	if err := json.NewDecoder(rawResp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("LookupEntity: decode: %w", err)
	}
	return &result, nil
}

// RenderPreview requests a PNG preview for a template from POST /api/render/preview.
// Returns the raw PNG bytes on success, or an error when the endpoint is unavailable
// or the render fails. Callers should treat any error as "show placeholder" — the
// endpoint is optional and may not yet be implemented by all backend versions.
func (c *HubClient) RenderPreview(ctx context.Context, templateKey string) ([]byte, error) {
	start := time.Now()
	previewURL := c.baseURL + "/api/render/preview?key=" + url.QueryEscape(templateKey)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, previewURL, nil)
	if err != nil {
		return nil, err
	}
	resp, err := c.hc.Do(req)
	logCall("RenderPreview", start, err)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("RenderPreview: status %d", resp.StatusCode)
	}
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return data, nil
}

// CheckHealth performs a GET /healthz against the backend and returns an error if unavailable.
func (c *HubClient) CheckHealth(ctx context.Context) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, c.baseURL+"/healthz", nil)
	if err != nil {
		return err
	}
	resp, err := c.hc.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("backend healthz: %d", resp.StatusCode)
	}
	return nil
}

// parseUUID parses a string into an openapi_types.UUID.
func parseUUID(s string) (openapi_types.UUID, error) {
	var u openapi_types.UUID
	err := u.UnmarshalText([]byte(s))
	return u, err
}
