// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for LookupResultApp.
const (
	LookupResultAppGrocy    LookupResultApp = "grocy"
	LookupResultAppSnipeit  LookupResultApp = "snipeit"
	LookupResultAppSpoolman LookupResultApp = "spoolman"
)

// Valid indicates whether the value is a known member of the LookupResultApp enum.
func (e LookupResultApp) Valid() bool {
	switch e {
	case LookupResultAppGrocy:
		return true
	case LookupResultAppSnipeit:
		return true
	case LookupResultAppSpoolman:
		return true
	default:
		return false
	}
}

// Defines values for LookupApiLookupAppEntityIdGetParamsApp.
const (
	LookupApiLookupAppEntityIdGetParamsAppGrocy    LookupApiLookupAppEntityIdGetParamsApp = "grocy"
	LookupApiLookupAppEntityIdGetParamsAppSnipeit  LookupApiLookupAppEntityIdGetParamsApp = "snipeit"
	LookupApiLookupAppEntityIdGetParamsAppSpoolman LookupApiLookupAppEntityIdGetParamsApp = "spoolman"
)

// Valid indicates whether the value is a known member of the LookupApiLookupAppEntityIdGetParamsApp enum.
func (e LookupApiLookupAppEntityIdGetParamsApp) Valid() bool {
	switch e {
	case LookupApiLookupAppEntityIdGetParamsAppGrocy:
		return true
	case LookupApiLookupAppEntityIdGetParamsAppSnipeit:
		return true
	case LookupApiLookupAppEntityIdGetParamsAppSpoolman:
		return true
	default:
		return false
	}
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// JobRead Serialised view of a Job DB row.
type JobRead struct {
	CreatedAt   time.Time               `json:"created_at"`
	Error       *string                 `json:"error"`
	FinishedAt  *time.Time              `json:"finished_at"`
	Id          openapi_types.UUID      `json:"id"`
	Payload     map[string]interface{}  `json:"payload"`
	PrinterId   openapi_types.UUID      `json:"printer_id"`
	Result      *map[string]interface{} `json:"result"`
	StartedAt   *time.Time              `json:"started_at"`
	State       string                  `json:"state"`
	TemplateKey string                  `json:"template_key"`
	UpdatedAt   time.Time               `json:"updated_at"`
}

// LookupResult REST view of a resolved integration entity.
type LookupResult struct {
	// App Integration app that resolved this entity
	App LookupResultApp `json:"app"`

	// Extra Integration-specific extras not covered by the core fields. Contents vary by app — see each integration's plugin docs.
	Extra *map[string]interface{} `json:"extra,omitempty"`

	// Id The entity identifier as supplied by the caller
	Id string `json:"id"`

	// Name Human-readable display name of the entity
	Name string `json:"name"`

	// Url Deep-link URL to the entity in the integration's web UI (e.g. Snipe-IT asset page, Grocy product page, Spoolman spool page)
	Url string `json:"url"`
}

// LookupResultApp Integration app that resolved this entity
type LookupResultApp string

// PrinterRead Full representation of a Printer row, augmented with the paused flag.
//
// “paused“ is joined from the “printer_state“ table; it defaults to
// “False“ for printers whose state row was not yet created (safe — the
// DB lifespan helper creates state rows at startup, so this only matters
// in tests or during the very first boot).
type PrinterRead struct {
	Backend    string                 `json:"backend"`
	Connection map[string]interface{} `json:"connection"`
	CreatedAt  time.Time              `json:"created_at"`
	Enabled    bool                   `json:"enabled"`
	Id         openapi_types.UUID     `json:"id"`
	Model      string                 `json:"model"`
	Name       string                 `json:"name"`
	Paused     bool                   `json:"paused"`
	UpdatedAt  time.Time              `json:"updated_at"`
}

// PrinterStatus Live status result from a fresh ESC i S probe + cache write-back.
//
// “tape_loaded“ is a human-readable string such as
// “"12mm laminated black/clear"“ or “None“ when no tape is inserted.
// “error_state“ mirrors the active PrinterError flags as a string, or
// “None“ when the printer is ready.
// “captured_at“ is the UTC timestamp of the probe that produced this
// block.
type PrinterStatus struct {
	CapturedAt time.Time `json:"captured_at"`

	// ErrorState Active error flags as a string; None when printer is ready
	ErrorState *string            `json:"error_state,omitempty"`
	Online     bool               `json:"online"`
	PrinterId  openapi_types.UUID `json:"printer_id"`

	// TapeLoaded e.g. "12mm laminated black/clear"; None when no tape is loaded
	TapeLoaded *string `json:"tape_loaded,omitempty"`
}

// ProblemDetail RFC 7807 Problem Details object.
//
// All fields are optional except “type“, “title“, and “status“.
// The “extensions“ field carries additional problem-type-specific
// context (e.g. “expected_mm“ / “loaded_mm“ for tape mismatches).
type ProblemDetail struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Extensions Additional problem-type-specific fields
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// Instance URI reference identifying this specific occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status int `json:"status"`

	// Title Short human-readable summary of the problem
	Title string `json:"title"`

	// Type URI reference identifying the problem type
	Type *string `json:"type,omitempty"`
}

// TemplateRead Serialised view of a Template DB row.
type TemplateRead struct {
	App           *string                `json:"app"`
	CreatedAt     time.Time              `json:"created_at"`
	Definition    map[string]interface{} `json:"definition"`
	Id            openapi_types.UUID     `json:"id"`
	Key           string                 `json:"key"`
	Name          string                 `json:"name"`
	PrinterModel  string                 `json:"printer_model"`
	SchemaVersion int                    `json:"schema_version"`
	Source        string                 `json:"source"`
	TapeWidthMm   int                    `json:"tape_width_mm"`
	UpdatedAt     time.Time              `json:"updated_at"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input interface{}                `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// SseEventsApiEventsGetParams defines parameters for SseEventsApiEventsGet.
type SseEventsApiEventsGetParams struct {
	PrinterId openapi_types.UUID `form:"printer_id" json:"printer_id"`
}

// ListJobsApiJobsGetParams defines parameters for ListJobsApiJobsGet.
type ListJobsApiJobsGetParams struct {
	// State Filter by job state (queued / printing / done / failed / …)
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// PrinterId Filter by printer UUID
	PrinterId *openapi_types.UUID `form:"printer_id,omitempty" json:"printer_id,omitempty"`

	// Since Return only jobs created at or after this ISO-8601 datetime
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`

	// Limit Maximum number of jobs to return (1-200, default 50)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// LookupApiLookupAppEntityIdGetParamsApp defines parameters for LookupApiLookupAppEntityIdGet.
type LookupApiLookupAppEntityIdGetParamsApp string

// ListTemplatesApiTemplatesGetParams defines parameters for ListTemplatesApiTemplatesGet.
type ListTemplatesApiTemplatesGetParams struct {
	// App Filter by integration app (snipeit / grocy / spoolman / …)
	App *string `form:"app,omitempty" json:"app,omitempty"`
}

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// SseEventsApiEventsGet request
	SseEventsApiEventsGet(ctx context.Context, params *SseEventsApiEventsGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListJobsApiJobsGet request
	ListJobsApiJobsGet(ctx context.Context, params *ListJobsApiJobsGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetJobApiJobsJobIdGet request
	GetJobApiJobsJobIdGet(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelJobApiJobsJobIdCancelPost request
	CancelJobApiJobsJobIdCancelPost(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PauseJobApiJobsJobIdPausePost request
	PauseJobApiJobsJobIdPausePost(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ResumeJobApiJobsJobIdResumePost request
	ResumeJobApiJobsJobIdResumePost(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RetryJobApiJobsJobIdRetryPost request
	RetryJobApiJobsJobIdRetryPost(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LookupApiLookupAppEntityIdGet request
	LookupApiLookupAppEntityIdGet(ctx context.Context, app LookupApiLookupAppEntityIdGetParamsApp, entityId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListPrintersApiPrintersGet request
	ListPrintersApiPrintersGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPrinterApiPrintersPrinterIdGet request
	GetPrinterApiPrintersPrinterIdGet(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PausePrinterApiPrintersPrinterIdPausePost request
	PausePrinterApiPrintersPrinterIdPausePost(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPrinterQueueApiPrintersPrinterIdQueueGet request
	GetPrinterQueueApiPrintersPrinterIdQueueGet(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ClearPrinterQueueApiPrintersPrinterIdQueueClearPost request
	ClearPrinterQueueApiPrintersPrinterIdQueueClearPost(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ResumePrinterApiPrintersPrinterIdResumePost request
	ResumePrinterApiPrintersPrinterIdResumePost(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPrinterStatusApiPrintersPrinterIdStatusGet request
	GetPrinterStatusApiPrintersPrinterIdStatusGet(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPrinterTapeApiPrintersPrinterIdTapeGet request
	GetPrinterTapeApiPrintersPrinterIdTapeGet(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListTemplatesApiTemplatesGet request
	ListTemplatesApiTemplatesGet(ctx context.Context, params *ListTemplatesApiTemplatesGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) SseEventsApiEventsGet(ctx context.Context, params *SseEventsApiEventsGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSseEventsApiEventsGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListJobsApiJobsGet(ctx context.Context, params *ListJobsApiJobsGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListJobsApiJobsGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetJobApiJobsJobIdGet(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetJobApiJobsJobIdGetRequest(c.Server, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CancelJobApiJobsJobIdCancelPost(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelJobApiJobsJobIdCancelPostRequest(c.Server, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PauseJobApiJobsJobIdPausePost(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPauseJobApiJobsJobIdPausePostRequest(c.Server, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResumeJobApiJobsJobIdResumePost(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResumeJobApiJobsJobIdResumePostRequest(c.Server, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RetryJobApiJobsJobIdRetryPost(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRetryJobApiJobsJobIdRetryPostRequest(c.Server, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LookupApiLookupAppEntityIdGet(ctx context.Context, app LookupApiLookupAppEntityIdGetParamsApp, entityId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLookupApiLookupAppEntityIdGetRequest(c.Server, app, entityId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListPrintersApiPrintersGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPrintersApiPrintersGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPrinterApiPrintersPrinterIdGet(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPrinterApiPrintersPrinterIdGetRequest(c.Server, printerId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PausePrinterApiPrintersPrinterIdPausePost(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPausePrinterApiPrintersPrinterIdPausePostRequest(c.Server, printerId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPrinterQueueApiPrintersPrinterIdQueueGet(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPrinterQueueApiPrintersPrinterIdQueueGetRequest(c.Server, printerId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ClearPrinterQueueApiPrintersPrinterIdQueueClearPost(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewClearPrinterQueueApiPrintersPrinterIdQueueClearPostRequest(c.Server, printerId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResumePrinterApiPrintersPrinterIdResumePost(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResumePrinterApiPrintersPrinterIdResumePostRequest(c.Server, printerId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPrinterStatusApiPrintersPrinterIdStatusGet(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPrinterStatusApiPrintersPrinterIdStatusGetRequest(c.Server, printerId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPrinterTapeApiPrintersPrinterIdTapeGet(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPrinterTapeApiPrintersPrinterIdTapeGetRequest(c.Server, printerId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListTemplatesApiTemplatesGet(ctx context.Context, params *ListTemplatesApiTemplatesGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListTemplatesApiTemplatesGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSseEventsApiEventsGetRequest generates requests for SseEventsApiEventsGet
func NewSseEventsApiEventsGetRequest(server string, params *SseEventsApiEventsGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "printer_id", params.PrinterId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "uuid"}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListJobsApiJobsGetRequest generates requests for ListJobsApiJobsGet
func NewListJobsApiJobsGetRequest(server string, params *ListJobsApiJobsGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/jobs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.State != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "state", *params.State, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PrinterId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "printer_id", *params.PrinterId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "uuid"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Since != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "since", *params.Since, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetJobApiJobsJobIdGetRequest generates requests for GetJobApiJobsJobIdGet
func NewGetJobApiJobsJobIdGetRequest(server string, jobId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "job_id", jobId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/jobs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCancelJobApiJobsJobIdCancelPostRequest generates requests for CancelJobApiJobsJobIdCancelPost
func NewCancelJobApiJobsJobIdCancelPostRequest(server string, jobId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "job_id", jobId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/jobs/%s/cancel", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPauseJobApiJobsJobIdPausePostRequest generates requests for PauseJobApiJobsJobIdPausePost
func NewPauseJobApiJobsJobIdPausePostRequest(server string, jobId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "job_id", jobId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/jobs/%s/pause", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewResumeJobApiJobsJobIdResumePostRequest generates requests for ResumeJobApiJobsJobIdResumePost
func NewResumeJobApiJobsJobIdResumePostRequest(server string, jobId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "job_id", jobId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/jobs/%s/resume", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRetryJobApiJobsJobIdRetryPostRequest generates requests for RetryJobApiJobsJobIdRetryPost
func NewRetryJobApiJobsJobIdRetryPostRequest(server string, jobId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "job_id", jobId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/jobs/%s/retry", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLookupApiLookupAppEntityIdGetRequest generates requests for LookupApiLookupAppEntityIdGet
func NewLookupApiLookupAppEntityIdGetRequest(server string, app LookupApiLookupAppEntityIdGetParamsApp, entityId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "app", app, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "entity_id", entityId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/lookup/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListPrintersApiPrintersGetRequest generates requests for ListPrintersApiPrintersGet
func NewListPrintersApiPrintersGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/printers")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPrinterApiPrintersPrinterIdGetRequest generates requests for GetPrinterApiPrintersPrinterIdGet
func NewGetPrinterApiPrintersPrinterIdGetRequest(server string, printerId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "printer_id", printerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/printers/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPausePrinterApiPrintersPrinterIdPausePostRequest generates requests for PausePrinterApiPrintersPrinterIdPausePost
func NewPausePrinterApiPrintersPrinterIdPausePostRequest(server string, printerId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "printer_id", printerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/printers/%s/pause", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPrinterQueueApiPrintersPrinterIdQueueGetRequest generates requests for GetPrinterQueueApiPrintersPrinterIdQueueGet
func NewGetPrinterQueueApiPrintersPrinterIdQueueGetRequest(server string, printerId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "printer_id", printerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/printers/%s/queue", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewClearPrinterQueueApiPrintersPrinterIdQueueClearPostRequest generates requests for ClearPrinterQueueApiPrintersPrinterIdQueueClearPost
func NewClearPrinterQueueApiPrintersPrinterIdQueueClearPostRequest(server string, printerId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "printer_id", printerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/printers/%s/queue/clear", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewResumePrinterApiPrintersPrinterIdResumePostRequest generates requests for ResumePrinterApiPrintersPrinterIdResumePost
func NewResumePrinterApiPrintersPrinterIdResumePostRequest(server string, printerId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "printer_id", printerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/printers/%s/resume", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPrinterStatusApiPrintersPrinterIdStatusGetRequest generates requests for GetPrinterStatusApiPrintersPrinterIdStatusGet
func NewGetPrinterStatusApiPrintersPrinterIdStatusGetRequest(server string, printerId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "printer_id", printerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/printers/%s/status", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPrinterTapeApiPrintersPrinterIdTapeGetRequest generates requests for GetPrinterTapeApiPrintersPrinterIdTapeGet
func NewGetPrinterTapeApiPrintersPrinterIdTapeGetRequest(server string, printerId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "printer_id", printerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/printers/%s/tape", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListTemplatesApiTemplatesGetRequest generates requests for ListTemplatesApiTemplatesGet
func NewListTemplatesApiTemplatesGetRequest(server string, params *ListTemplatesApiTemplatesGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/templates")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.App != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "app", *params.App, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// SseEventsApiEventsGetWithResponse request
	SseEventsApiEventsGetWithResponse(ctx context.Context, params *SseEventsApiEventsGetParams, reqEditors ...RequestEditorFn) (*SseEventsApiEventsGetResponse, error)

	// ListJobsApiJobsGetWithResponse request
	ListJobsApiJobsGetWithResponse(ctx context.Context, params *ListJobsApiJobsGetParams, reqEditors ...RequestEditorFn) (*ListJobsApiJobsGetResponse, error)

	// GetJobApiJobsJobIdGetWithResponse request
	GetJobApiJobsJobIdGetWithResponse(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetJobApiJobsJobIdGetResponse, error)

	// CancelJobApiJobsJobIdCancelPostWithResponse request
	CancelJobApiJobsJobIdCancelPostWithResponse(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*CancelJobApiJobsJobIdCancelPostResponse, error)

	// PauseJobApiJobsJobIdPausePostWithResponse request
	PauseJobApiJobsJobIdPausePostWithResponse(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*PauseJobApiJobsJobIdPausePostResponse, error)

	// ResumeJobApiJobsJobIdResumePostWithResponse request
	ResumeJobApiJobsJobIdResumePostWithResponse(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*ResumeJobApiJobsJobIdResumePostResponse, error)

	// RetryJobApiJobsJobIdRetryPostWithResponse request
	RetryJobApiJobsJobIdRetryPostWithResponse(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*RetryJobApiJobsJobIdRetryPostResponse, error)

	// LookupApiLookupAppEntityIdGetWithResponse request
	LookupApiLookupAppEntityIdGetWithResponse(ctx context.Context, app LookupApiLookupAppEntityIdGetParamsApp, entityId string, reqEditors ...RequestEditorFn) (*LookupApiLookupAppEntityIdGetResponse, error)

	// ListPrintersApiPrintersGetWithResponse request
	ListPrintersApiPrintersGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListPrintersApiPrintersGetResponse, error)

	// GetPrinterApiPrintersPrinterIdGetWithResponse request
	GetPrinterApiPrintersPrinterIdGetWithResponse(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetPrinterApiPrintersPrinterIdGetResponse, error)

	// PausePrinterApiPrintersPrinterIdPausePostWithResponse request
	PausePrinterApiPrintersPrinterIdPausePostWithResponse(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*PausePrinterApiPrintersPrinterIdPausePostResponse, error)

	// GetPrinterQueueApiPrintersPrinterIdQueueGetWithResponse request
	GetPrinterQueueApiPrintersPrinterIdQueueGetWithResponse(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetPrinterQueueApiPrintersPrinterIdQueueGetResponse, error)

	// ClearPrinterQueueApiPrintersPrinterIdQueueClearPostWithResponse request
	ClearPrinterQueueApiPrintersPrinterIdQueueClearPostWithResponse(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*ClearPrinterQueueApiPrintersPrinterIdQueueClearPostResponse, error)

	// ResumePrinterApiPrintersPrinterIdResumePostWithResponse request
	ResumePrinterApiPrintersPrinterIdResumePostWithResponse(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*ResumePrinterApiPrintersPrinterIdResumePostResponse, error)

	// GetPrinterStatusApiPrintersPrinterIdStatusGetWithResponse request
	GetPrinterStatusApiPrintersPrinterIdStatusGetWithResponse(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetPrinterStatusApiPrintersPrinterIdStatusGetResponse, error)

	// GetPrinterTapeApiPrintersPrinterIdTapeGetWithResponse request
	GetPrinterTapeApiPrintersPrinterIdTapeGetWithResponse(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetPrinterTapeApiPrintersPrinterIdTapeGetResponse, error)

	// ListTemplatesApiTemplatesGetWithResponse request
	ListTemplatesApiTemplatesGetWithResponse(ctx context.Context, params *ListTemplatesApiTemplatesGetParams, reqEditors ...RequestEditorFn) (*ListTemplatesApiTemplatesGetResponse, error)
}

type SseEventsApiEventsGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r SseEventsApiEventsGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SseEventsApiEventsGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SseEventsApiEventsGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListJobsApiJobsGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]JobRead
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r ListJobsApiJobsGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListJobsApiJobsGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListJobsApiJobsGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetJobApiJobsJobIdGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JobRead
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetJobApiJobsJobIdGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetJobApiJobsJobIdGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetJobApiJobsJobIdGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CancelJobApiJobsJobIdCancelPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JobRead
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r CancelJobApiJobsJobIdCancelPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelJobApiJobsJobIdCancelPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CancelJobApiJobsJobIdCancelPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PauseJobApiJobsJobIdPausePostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *HTTPValidationError
	JSON501      *ProblemDetail
}

// Status returns HTTPResponse.Status
func (r PauseJobApiJobsJobIdPausePostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PauseJobApiJobsJobIdPausePostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PauseJobApiJobsJobIdPausePostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ResumeJobApiJobsJobIdResumePostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *HTTPValidationError
	JSON501      *ProblemDetail
}

// Status returns HTTPResponse.Status
func (r ResumeJobApiJobsJobIdResumePostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ResumeJobApiJobsJobIdResumePostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ResumeJobApiJobsJobIdResumePostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RetryJobApiJobsJobIdRetryPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *JobRead
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r RetryJobApiJobsJobIdRetryPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RetryJobApiJobsJobIdRetryPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RetryJobApiJobsJobIdRetryPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type LookupApiLookupAppEntityIdGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LookupResult
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r LookupApiLookupAppEntityIdGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LookupApiLookupAppEntityIdGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r LookupApiLookupAppEntityIdGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListPrintersApiPrintersGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]PrinterRead
}

// Status returns HTTPResponse.Status
func (r ListPrintersApiPrintersGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPrintersApiPrintersGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListPrintersApiPrintersGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPrinterApiPrintersPrinterIdGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PrinterRead
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetPrinterApiPrintersPrinterIdGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPrinterApiPrintersPrinterIdGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPrinterApiPrintersPrinterIdGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PausePrinterApiPrintersPrinterIdPausePostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r PausePrinterApiPrintersPrinterIdPausePostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PausePrinterApiPrintersPrinterIdPausePostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PausePrinterApiPrintersPrinterIdPausePostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPrinterQueueApiPrintersPrinterIdQueueGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]map[string]interface{}
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetPrinterQueueApiPrintersPrinterIdQueueGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPrinterQueueApiPrintersPrinterIdQueueGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPrinterQueueApiPrintersPrinterIdQueueGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ClearPrinterQueueApiPrintersPrinterIdQueueClearPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r ClearPrinterQueueApiPrintersPrinterIdQueueClearPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ClearPrinterQueueApiPrintersPrinterIdQueueClearPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ClearPrinterQueueApiPrintersPrinterIdQueueClearPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ResumePrinterApiPrintersPrinterIdResumePostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r ResumePrinterApiPrintersPrinterIdResumePostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ResumePrinterApiPrintersPrinterIdResumePostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ResumePrinterApiPrintersPrinterIdResumePostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPrinterStatusApiPrintersPrinterIdStatusGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PrinterStatus
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetPrinterStatusApiPrintersPrinterIdStatusGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPrinterStatusApiPrintersPrinterIdStatusGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPrinterStatusApiPrintersPrinterIdStatusGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPrinterTapeApiPrintersPrinterIdTapeGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetPrinterTapeApiPrintersPrinterIdTapeGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPrinterTapeApiPrintersPrinterIdTapeGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPrinterTapeApiPrintersPrinterIdTapeGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListTemplatesApiTemplatesGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]TemplateRead
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r ListTemplatesApiTemplatesGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListTemplatesApiTemplatesGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListTemplatesApiTemplatesGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// SseEventsApiEventsGetWithResponse request returning *SseEventsApiEventsGetResponse
func (c *ClientWithResponses) SseEventsApiEventsGetWithResponse(ctx context.Context, params *SseEventsApiEventsGetParams, reqEditors ...RequestEditorFn) (*SseEventsApiEventsGetResponse, error) {
	rsp, err := c.SseEventsApiEventsGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSseEventsApiEventsGetResponse(rsp)
}

// ListJobsApiJobsGetWithResponse request returning *ListJobsApiJobsGetResponse
func (c *ClientWithResponses) ListJobsApiJobsGetWithResponse(ctx context.Context, params *ListJobsApiJobsGetParams, reqEditors ...RequestEditorFn) (*ListJobsApiJobsGetResponse, error) {
	rsp, err := c.ListJobsApiJobsGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListJobsApiJobsGetResponse(rsp)
}

// GetJobApiJobsJobIdGetWithResponse request returning *GetJobApiJobsJobIdGetResponse
func (c *ClientWithResponses) GetJobApiJobsJobIdGetWithResponse(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetJobApiJobsJobIdGetResponse, error) {
	rsp, err := c.GetJobApiJobsJobIdGet(ctx, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetJobApiJobsJobIdGetResponse(rsp)
}

// CancelJobApiJobsJobIdCancelPostWithResponse request returning *CancelJobApiJobsJobIdCancelPostResponse
func (c *ClientWithResponses) CancelJobApiJobsJobIdCancelPostWithResponse(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*CancelJobApiJobsJobIdCancelPostResponse, error) {
	rsp, err := c.CancelJobApiJobsJobIdCancelPost(ctx, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelJobApiJobsJobIdCancelPostResponse(rsp)
}

// PauseJobApiJobsJobIdPausePostWithResponse request returning *PauseJobApiJobsJobIdPausePostResponse
func (c *ClientWithResponses) PauseJobApiJobsJobIdPausePostWithResponse(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*PauseJobApiJobsJobIdPausePostResponse, error) {
	rsp, err := c.PauseJobApiJobsJobIdPausePost(ctx, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePauseJobApiJobsJobIdPausePostResponse(rsp)
}

// ResumeJobApiJobsJobIdResumePostWithResponse request returning *ResumeJobApiJobsJobIdResumePostResponse
func (c *ClientWithResponses) ResumeJobApiJobsJobIdResumePostWithResponse(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*ResumeJobApiJobsJobIdResumePostResponse, error) {
	rsp, err := c.ResumeJobApiJobsJobIdResumePost(ctx, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResumeJobApiJobsJobIdResumePostResponse(rsp)
}

// RetryJobApiJobsJobIdRetryPostWithResponse request returning *RetryJobApiJobsJobIdRetryPostResponse
func (c *ClientWithResponses) RetryJobApiJobsJobIdRetryPostWithResponse(ctx context.Context, jobId openapi_types.UUID, reqEditors ...RequestEditorFn) (*RetryJobApiJobsJobIdRetryPostResponse, error) {
	rsp, err := c.RetryJobApiJobsJobIdRetryPost(ctx, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRetryJobApiJobsJobIdRetryPostResponse(rsp)
}

// LookupApiLookupAppEntityIdGetWithResponse request returning *LookupApiLookupAppEntityIdGetResponse
func (c *ClientWithResponses) LookupApiLookupAppEntityIdGetWithResponse(ctx context.Context, app LookupApiLookupAppEntityIdGetParamsApp, entityId string, reqEditors ...RequestEditorFn) (*LookupApiLookupAppEntityIdGetResponse, error) {
	rsp, err := c.LookupApiLookupAppEntityIdGet(ctx, app, entityId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLookupApiLookupAppEntityIdGetResponse(rsp)
}

// ListPrintersApiPrintersGetWithResponse request returning *ListPrintersApiPrintersGetResponse
func (c *ClientWithResponses) ListPrintersApiPrintersGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListPrintersApiPrintersGetResponse, error) {
	rsp, err := c.ListPrintersApiPrintersGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPrintersApiPrintersGetResponse(rsp)
}

// GetPrinterApiPrintersPrinterIdGetWithResponse request returning *GetPrinterApiPrintersPrinterIdGetResponse
func (c *ClientWithResponses) GetPrinterApiPrintersPrinterIdGetWithResponse(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetPrinterApiPrintersPrinterIdGetResponse, error) {
	rsp, err := c.GetPrinterApiPrintersPrinterIdGet(ctx, printerId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPrinterApiPrintersPrinterIdGetResponse(rsp)
}

// PausePrinterApiPrintersPrinterIdPausePostWithResponse request returning *PausePrinterApiPrintersPrinterIdPausePostResponse
func (c *ClientWithResponses) PausePrinterApiPrintersPrinterIdPausePostWithResponse(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*PausePrinterApiPrintersPrinterIdPausePostResponse, error) {
	rsp, err := c.PausePrinterApiPrintersPrinterIdPausePost(ctx, printerId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePausePrinterApiPrintersPrinterIdPausePostResponse(rsp)
}

// GetPrinterQueueApiPrintersPrinterIdQueueGetWithResponse request returning *GetPrinterQueueApiPrintersPrinterIdQueueGetResponse
func (c *ClientWithResponses) GetPrinterQueueApiPrintersPrinterIdQueueGetWithResponse(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetPrinterQueueApiPrintersPrinterIdQueueGetResponse, error) {
	rsp, err := c.GetPrinterQueueApiPrintersPrinterIdQueueGet(ctx, printerId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPrinterQueueApiPrintersPrinterIdQueueGetResponse(rsp)
}

// ClearPrinterQueueApiPrintersPrinterIdQueueClearPostWithResponse request returning *ClearPrinterQueueApiPrintersPrinterIdQueueClearPostResponse
func (c *ClientWithResponses) ClearPrinterQueueApiPrintersPrinterIdQueueClearPostWithResponse(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*ClearPrinterQueueApiPrintersPrinterIdQueueClearPostResponse, error) {
	rsp, err := c.ClearPrinterQueueApiPrintersPrinterIdQueueClearPost(ctx, printerId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseClearPrinterQueueApiPrintersPrinterIdQueueClearPostResponse(rsp)
}

// ResumePrinterApiPrintersPrinterIdResumePostWithResponse request returning *ResumePrinterApiPrintersPrinterIdResumePostResponse
func (c *ClientWithResponses) ResumePrinterApiPrintersPrinterIdResumePostWithResponse(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*ResumePrinterApiPrintersPrinterIdResumePostResponse, error) {
	rsp, err := c.ResumePrinterApiPrintersPrinterIdResumePost(ctx, printerId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResumePrinterApiPrintersPrinterIdResumePostResponse(rsp)
}

// GetPrinterStatusApiPrintersPrinterIdStatusGetWithResponse request returning *GetPrinterStatusApiPrintersPrinterIdStatusGetResponse
func (c *ClientWithResponses) GetPrinterStatusApiPrintersPrinterIdStatusGetWithResponse(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetPrinterStatusApiPrintersPrinterIdStatusGetResponse, error) {
	rsp, err := c.GetPrinterStatusApiPrintersPrinterIdStatusGet(ctx, printerId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPrinterStatusApiPrintersPrinterIdStatusGetResponse(rsp)
}

// GetPrinterTapeApiPrintersPrinterIdTapeGetWithResponse request returning *GetPrinterTapeApiPrintersPrinterIdTapeGetResponse
func (c *ClientWithResponses) GetPrinterTapeApiPrintersPrinterIdTapeGetWithResponse(ctx context.Context, printerId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetPrinterTapeApiPrintersPrinterIdTapeGetResponse, error) {
	rsp, err := c.GetPrinterTapeApiPrintersPrinterIdTapeGet(ctx, printerId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPrinterTapeApiPrintersPrinterIdTapeGetResponse(rsp)
}

// ListTemplatesApiTemplatesGetWithResponse request returning *ListTemplatesApiTemplatesGetResponse
func (c *ClientWithResponses) ListTemplatesApiTemplatesGetWithResponse(ctx context.Context, params *ListTemplatesApiTemplatesGetParams, reqEditors ...RequestEditorFn) (*ListTemplatesApiTemplatesGetResponse, error) {
	rsp, err := c.ListTemplatesApiTemplatesGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListTemplatesApiTemplatesGetResponse(rsp)
}

// ParseSseEventsApiEventsGetResponse parses an HTTP response from a SseEventsApiEventsGetWithResponse call
func ParseSseEventsApiEventsGetResponse(rsp *http.Response) (*SseEventsApiEventsGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SseEventsApiEventsGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseListJobsApiJobsGetResponse parses an HTTP response from a ListJobsApiJobsGetWithResponse call
func ParseListJobsApiJobsGetResponse(rsp *http.Response) (*ListJobsApiJobsGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListJobsApiJobsGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []JobRead
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetJobApiJobsJobIdGetResponse parses an HTTP response from a GetJobApiJobsJobIdGetWithResponse call
func ParseGetJobApiJobsJobIdGetResponse(rsp *http.Response) (*GetJobApiJobsJobIdGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetJobApiJobsJobIdGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JobRead
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseCancelJobApiJobsJobIdCancelPostResponse parses an HTTP response from a CancelJobApiJobsJobIdCancelPostWithResponse call
func ParseCancelJobApiJobsJobIdCancelPostResponse(rsp *http.Response) (*CancelJobApiJobsJobIdCancelPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelJobApiJobsJobIdCancelPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JobRead
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParsePauseJobApiJobsJobIdPausePostResponse parses an HTTP response from a PauseJobApiJobsJobIdPausePostWithResponse call
func ParsePauseJobApiJobsJobIdPausePostResponse(rsp *http.Response) (*PauseJobApiJobsJobIdPausePostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PauseJobApiJobsJobIdPausePostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 501:
		var dest ProblemDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON501 = &dest

	}

	return response, nil
}

// ParseResumeJobApiJobsJobIdResumePostResponse parses an HTTP response from a ResumeJobApiJobsJobIdResumePostWithResponse call
func ParseResumeJobApiJobsJobIdResumePostResponse(rsp *http.Response) (*ResumeJobApiJobsJobIdResumePostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ResumeJobApiJobsJobIdResumePostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 501:
		var dest ProblemDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON501 = &dest

	}

	return response, nil
}

// ParseRetryJobApiJobsJobIdRetryPostResponse parses an HTTP response from a RetryJobApiJobsJobIdRetryPostWithResponse call
func ParseRetryJobApiJobsJobIdRetryPostResponse(rsp *http.Response) (*RetryJobApiJobsJobIdRetryPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RetryJobApiJobsJobIdRetryPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest JobRead
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseLookupApiLookupAppEntityIdGetResponse parses an HTTP response from a LookupApiLookupAppEntityIdGetWithResponse call
func ParseLookupApiLookupAppEntityIdGetResponse(rsp *http.Response) (*LookupApiLookupAppEntityIdGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LookupApiLookupAppEntityIdGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LookupResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseListPrintersApiPrintersGetResponse parses an HTTP response from a ListPrintersApiPrintersGetWithResponse call
func ParseListPrintersApiPrintersGetResponse(rsp *http.Response) (*ListPrintersApiPrintersGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPrintersApiPrintersGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []PrinterRead
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetPrinterApiPrintersPrinterIdGetResponse parses an HTTP response from a GetPrinterApiPrintersPrinterIdGetWithResponse call
func ParseGetPrinterApiPrintersPrinterIdGetResponse(rsp *http.Response) (*GetPrinterApiPrintersPrinterIdGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPrinterApiPrintersPrinterIdGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PrinterRead
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParsePausePrinterApiPrintersPrinterIdPausePostResponse parses an HTTP response from a PausePrinterApiPrintersPrinterIdPausePostWithResponse call
func ParsePausePrinterApiPrintersPrinterIdPausePostResponse(rsp *http.Response) (*PausePrinterApiPrintersPrinterIdPausePostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PausePrinterApiPrintersPrinterIdPausePostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetPrinterQueueApiPrintersPrinterIdQueueGetResponse parses an HTTP response from a GetPrinterQueueApiPrintersPrinterIdQueueGetWithResponse call
func ParseGetPrinterQueueApiPrintersPrinterIdQueueGetResponse(rsp *http.Response) (*GetPrinterQueueApiPrintersPrinterIdQueueGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPrinterQueueApiPrintersPrinterIdQueueGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseClearPrinterQueueApiPrintersPrinterIdQueueClearPostResponse parses an HTTP response from a ClearPrinterQueueApiPrintersPrinterIdQueueClearPostWithResponse call
func ParseClearPrinterQueueApiPrintersPrinterIdQueueClearPostResponse(rsp *http.Response) (*ClearPrinterQueueApiPrintersPrinterIdQueueClearPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ClearPrinterQueueApiPrintersPrinterIdQueueClearPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseResumePrinterApiPrintersPrinterIdResumePostResponse parses an HTTP response from a ResumePrinterApiPrintersPrinterIdResumePostWithResponse call
func ParseResumePrinterApiPrintersPrinterIdResumePostResponse(rsp *http.Response) (*ResumePrinterApiPrintersPrinterIdResumePostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ResumePrinterApiPrintersPrinterIdResumePostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetPrinterStatusApiPrintersPrinterIdStatusGetResponse parses an HTTP response from a GetPrinterStatusApiPrintersPrinterIdStatusGetWithResponse call
func ParseGetPrinterStatusApiPrintersPrinterIdStatusGetResponse(rsp *http.Response) (*GetPrinterStatusApiPrintersPrinterIdStatusGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPrinterStatusApiPrintersPrinterIdStatusGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PrinterStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetPrinterTapeApiPrintersPrinterIdTapeGetResponse parses an HTTP response from a GetPrinterTapeApiPrintersPrinterIdTapeGetWithResponse call
func ParseGetPrinterTapeApiPrintersPrinterIdTapeGetResponse(rsp *http.Response) (*GetPrinterTapeApiPrintersPrinterIdTapeGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPrinterTapeApiPrintersPrinterIdTapeGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseListTemplatesApiTemplatesGetResponse parses an HTTP response from a ListTemplatesApiTemplatesGetWithResponse call
func ParseListTemplatesApiTemplatesGetResponse(rsp *http.Response) (*ListTemplatesApiTemplatesGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListTemplatesApiTemplatesGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []TemplateRead
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
